import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, decimal, json } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", { id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull() });
export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert;

export const recoveryRuns = mysqlTable("recovery_runs", { id: varchar("id", { length: 64 }).primaryKey(), startedAt: timestamp("startedAt").notNull(), finishedAt: timestamp("finishedAt"), status: mysqlEnum("status", ["queued", "running", "completed"]).notNull(), totalAtRisk: decimal("totalAtRisk", { precision: 14, scale: 2 }).notNull(), totalRecovered: decimal("totalRecovered", { precision: 14, scale: 2 }).notNull(), eventCount: int("eventCount").notNull() });
export const recoveryCases = mysqlTable("recovery_cases", { id: varchar("id", { length: 64 }).primaryKey(), runId: varchar("runId", { length: 64 }).notNull(), merchantId: varchar("merchantId", { length: 64 }).notNull(), merchantName: varchar("merchantName", { length: 180 }).notNull(), amount: decimal("amount", { precision: 14, scale: 2 }).notNull(), paymentStatus: varchar("paymentStatus", { length: 40 }).notNull(), declineCode: varchar("declineCode", { length: 64 }), attemptCount: int("attemptCount").notNull(), rootCause: varchar("rootCause", { length: 64 }), confidence: decimal("confidence", { precision: 5, scale: 4 }), recommendedAction: varchar("recommendedAction", { length: 64 }), actionGated: int("actionGated").notNull(), gateReason: text("gateReason"), actionResult: varchar("actionResult", { length: 40 }), amountRecovered: decimal("amountRecovered", { precision: 14, scale: 2 }).notNull(), createdAt: timestamp("createdAt").notNull() });
export const recoveryAuditEvents = mysqlTable("recovery_audit_events", { id: varchar("id", { length: 64 }).primaryKey(), eventId: varchar("eventId", { length: 64 }).notNull(), stepName: varchar("stepName", { length: 40 }).notNull(), detailJson: json("detailJson").notNull(), timestamp: timestamp("timestamp").notNull() });
export const recoveryApprovals = mysqlTable("recovery_approvals", { id: varchar("id", { length: 64 }).primaryKey(), eventId: varchar("eventId", { length: 64 }).notNull(), status: mysqlEnum("status", ["pending", "approved", "rejected"]).notNull(), reviewedBy: varchar("reviewedBy", { length: 180 }), reviewedAt: timestamp("reviewedAt") });
export const policyRules = mysqlTable("policy_rules", { id: varchar("id", { length: 64 }).primaryKey(), rootCause: varchar("rootCause", { length: 64 }).notNull(), action: varchar("action", { length: 64 }).notNull(), maxRetries: int("maxRetries").notNull(), cooldownMinutes: int("cooldownMinutes").notNull(), amountCeiling: decimal("amountCeiling", { precision: 14, scale: 2 }).notNull(), confidenceFloor: decimal("confidenceFloor", { precision: 5, scale: 4 }).notNull(), permittedChannels: json("permittedChannels").notNull(), requiresApproval: int("requiresApproval").notNull(), updatedAt: timestamp("updatedAt").notNull() });
export type RecoveryRun = typeof recoveryRuns.$inferSelect; export type RecoveryCase = typeof recoveryCases.$inferSelect; export type RecoveryApproval = typeof recoveryApprovals.$inferSelect; export type PolicyRule = typeof policyRules.$inferSelect;
